name = "precision-pdf-pages"
main = "worker/index.ts"
compatibility_date = "2026-06-19"
workers_dev = true

[assets]
directory = "./out"
binding = "ASSETS"
run_worker_first = true
html_handling = "auto-trailing-slash"
not_found_handling = "404-page"

[[routes]]
pattern = "removepdfpages.net"
custom_domain = true

[[routes]]
pattern = "www.removepdfpages.net"
custom_domain = true
